### ISSUE TITLE
Symlink Failing (error: unknown package: telescope-plugin-hero)

### ISSUE THREAD

**Issue by kaona** [jshimko/telescope-datalook#9]
I tried updating Meteorite but that did not help...
Below is the command and resulting error:
````
~ $ cd GitHub/Telescope/
Kaona (telescope-datalook *) Telescope $ mrt add telescope-datalook

Done installing smart packages
/usr/local/lib/node_modules/meteorite/lib/meteor.js:145
          throw error;
                ^
Error: Command failed: /bin/sh -c meteor list
=> Errors while initializing project:

While selecting package versions:
error: unknown package: telescope-plugin-hero


    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
````

**Comment by jshimko** [comment]
Sorry, the instructions in the README were very outdated.  This package is pretty specific to Datalook.io and I'm the only person working on it, so I assumed updating the development docs was a fairly low priority.  I just pushed a bunch of edits to the README that outline how you should set things up now.  (meteorite is no longer in use)

Also, the hero plugin can be installed with `meteor add jeremy:telescope-plugin-hero` (more info at the repo [here][1])

[1]: https://github.com/jshimko/telescope-plugin-hero

**Comment by kaona** [comment]
Thank you, sir. I updated the hero plugin yesterday before seeing this. Going to run through it all again. I love the look of this. If I knew what I was doing, I would help you. Random question: if you wanted to teach your brother or older kid to help you with what you are working on, what would you send him to learn?

Will give you an update after i run through this.

**Comment by jshimko** [comment]
One of the best resources out there for learning Meteor and Telescope is the [Discover Meteor][1] book (and their [blog][2]).  The book teaches you all of the Meteor foundations while building a simpler version of Telescope (called Microscope) from scratch.  

Another great resource is [Evented Mind][3].  It's a screencast based training site that's focused on Meteor, Node, and Javascript in general.  They have a decent amount of free content, but I also highly recommend the paid plan.  The content is excellent and Chris is a great teacher.

Other than that, it's just code, code, code.  Nothing is better for learning this stuff than getting out there and doing it.  Pick a project you want to work on and just dig in as often as possible.  Eventually it all starts making sense!  

Good luck!

[1]: https://www.discovermeteor.com 
[2]: https://www.discovermeteor.com/blog
[3]: https://www.eventedmind.com/

**Comment by kaona** [comment]
So, if there is no .bashrc file, are expected to create it? If so, where is the recommended place for that? Perhaps next to the .bash_profile and other bash files in meteor? Thank you. Sorry for the rookie question.

**Comment by kaona** [comment]
Thank you, very much for the guidance on structuring the learning! Greatly appreciated.

**Comment by jshimko** [comment]
The `.bashrc` file goes in your home directory (assuming you're on OSX or Linux).  You can create one if it doesn't exist.  (Google bashrc and you'll find tons of resources for that)

If you want to skip that file altogether, you can also add environment variables before the Meteor command when starting up the app.  So something like...
```bash
# when starting meteor...
PACKAGE_DIRS="/Users/YOU/code/packages meteor
```

**Comment by kaona** [comment]
Thank you. I googled it prior to bothering you. Needed clarification if it was meteor specific. Wondered why it wasnt there if we need it.  Thanks for the guidance.

**Comment by jshimko** [comment]
You're welcome.  :)
